# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('safe', models.CharField(blank=True, max_length=28)),
                ('folder', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(choices=[('OS', 'Operating System'), ('DB', 'Database'), ('AP', 'Application')], default='OS', max_length=2)),
                ('policy_id', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=25)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('risk_rank', models.PositiveSmallIntegerField(blank=True, choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], default=1)),
                ('operational_impact', models.PositiveSmallIntegerField(blank=True, choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], default=1)),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, default=1)),
            ],
        ),
    ]
